# Site settings
title: "Anton Ipsen"
email: aoipsen@mit.edu
description: "Just a blog"
baseurl: ""
url: "https://aoipsen.github.io/"
title_description: "Anton Ipsen's Website"
title_image: "https://avatars.githubusercontent.com/u/58310996?s=400&u=ea0b2078a8ece760b32e3ade43338bdc6f65fed6&v=4"
google_analytics: 
disqus_account: 
github_repository: https://github.com/aoipsen
addthis_id: ra-513c6fa83da6ec67
post_limit: 0

# Social usernames/URLs
twitter_username: a_ipsen
github_username:  aoipsen
instagram_username: aoipsen
reddit_username: 
linkedin_link: https://www.linkedin.com/in/aoipsen/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "&copy; 2017 <a href=\"https://www.linkedin.com/in/aoipsen\">Anton Ipsen</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
